package cli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"testing"
)

// effortAllowed is the constraint table's --effort vocabulary (the six rating
// levels, ascending); the tests assert against it so both sides stay in sync.
var effortAllowed = constraints["effort"].Allowed

func TestStructuredArguments(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	for _, tc := range []struct {
		args    []string
		name    string
		value   any
		allowed []string
	}{
		{[]string{"--effort", "tiny"}, "effort", "tiny", effortAllowed},
		{[]string{"--unknown", "maybe"}, "unknown", "maybe", []string{"include", "exclude"}},
		{[]string{"add", "--title", "x", "--kind", "other"}, "kind", "other", []string{"project", "media"}},
		{[]string{"add", "--title", "x", "--kind", "project", "--status", "bogus"}, "status", "bogus", []string{"not_started", "in_progress", "done", "dropped"}},
		{[]string{"edit", "x", "--status", "bogus"}, "status", "bogus", []string{"not_started", "in_progress", "done", "dropped"}},
		{[]string{"--budget", "NaN"}, "budget", "NaN", nil},
		{[]string{"--limit", "-1"}, "limit", "-1", nil},
		{[]string{"--session", "later"}, "session", "later", nil},
		{[]string{"--session", "-1h"}, "session", "-1h", nil},
		{[]string{"--effort"}, "effort", nil, effortAllowed},
		{[]string{"add", "--title", "x", "--kind", "media", "--quality", "2"}, "quality", "2", nil},
		{[]string{"add", "--title", "x", "--kind", "media", "--deadline", "2026-02-30"}, "deadline", "2026-02-30", nil},
		{[]string{"completion", "bad"}, "shell", "bad", []string{"bash", "zsh", "fish"}},
		{[]string{"export", "bad"}, "format", "bad", []string{"json"}},
		{[]string{"export", "tsv"}, "format", "tsv", []string{"json"}},
		{[]string{"--lang", "bad"}, "lang", "bad", []string{"en", "sv"}},
		{[]string{"--kind", "nope"}, "kind", "nope", []string{"project", "media", "both"}},
		{[]string{"add", "--title", "x", "--kind", "both"}, "kind", "both", []string{"project", "media"}},
	} {
		t.Run(strings.Join(tc.args, " "), func(t *testing.T) {
			db := filepath.Join(t.TempDir(), "missing.db")
			code, _, stderr := invoke(t, db, tc.args...)
			if code != 2 {
				t.Fatalf("exit %d: %s", code, stderr)
			}
			var result struct {
				Error struct {
					Code, Argument string
					Value          any
					Allowed        []string
				}
			}
			if err := json.Unmarshal([]byte(stderr), &result); err != nil {
				t.Fatal(err)
			}
			e := result.Error
			if e.Code != "INVALID_ARGUMENT" || e.Argument != tc.name || e.Value != tc.value || !reflect.DeepEqual(e.Allowed, tc.allowed) {
				t.Fatal(stderr)
			}
			if _, err := os.Stat(db); !os.IsNotExist(err) {
				t.Fatal("invalid argument created store")
			}
		})
	}
}

// TestKindFilterBothAccepted: "both" is a valid value of the query kind filter
// (projects ∪ media); it is rejected for the entry kind, which is tested in
// TestStructuredArguments.
func TestKindFilterBothAccepted(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	db := filepath.Join(t.TempDir(), "list.db")
	for _, args := range [][]string{{"--kind", "both", "--peek"}, {"suggest", "--kind", "both", "--peek"}, {"list", "--kind", "both"}} {
		code, _, stderr := invoke(t, db, args...)
		if code != 1 || !strings.Contains(stderr, "NO_STORE") {
			t.Fatalf("%v: exit %d (parse would be 2): %s", args, code, stderr)
		}
	}
}

// Validate the JSON Schema subset generated by jsonShape against real CLI output.
// This catches emitter/schema drift, required-key omissions, and wrong field types.
func checkShape(value any, shape map[string]any, path string) error {
	if variants, ok := shape["anyOf"].([]any); ok {
		for _, variant := range variants {
			if checkShape(value, variant.(map[string]any), path) == nil {
				return nil
			}
		}
		return fmt.Errorf("%s matches no variant: %v", path, value)
	}
	typ := "null"
	switch value.(type) {
	case map[string]any:
		typ = "object"
	case []any:
		typ = "array"
	case string:
		typ = "string"
	case bool:
		typ = "boolean"
	case float64:
		typ = "number"
	}
	types := []string{}
	switch want := shape["type"].(type) {
	case string:
		types = append(types, want)
	case []any:
		for _, v := range want {
			types = append(types, v.(string))
		}
	}
	if typ == "number" && slices.Contains(types, "integer") {
		if v := value.(float64); v != float64(int64(v)) {
			return fmt.Errorf("%s not integer", path)
		}
		typ = "integer"
	}
	if len(types) > 0 && !slices.Contains(types, typ) {
		return fmt.Errorf("%s: got %s, want %v", path, typ, types)
	}
	if obj, ok := value.(map[string]any); ok {
		if required, ok := shape["required"].([]any); ok {
			for _, key := range required {
				if _, ok := obj[key.(string)]; !ok {
					return fmt.Errorf("%s missing %s", path, key)
				}
			}
		}
		props, _ := shape["properties"].(map[string]any)
		for key, v := range obj {
			sub, ok := props[key].(map[string]any)
			if !ok {
				sub, _ = shape["additionalProperties"].(map[string]any)
			}
			if err := checkShape(v, sub, path+"."+key); err != nil {
				return err
			}
		}
	}
	if array, ok := value.([]any); ok {
		sub, _ := shape["items"].(map[string]any)
		for i, v := range array {
			if err := checkShape(v, sub, fmt.Sprintf("%s[%d]", path, i)); err != nil {
				return err
			}
		}
	}
	return nil
}
func TestCommandResponseSchemas(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	db := filepath.Join(t.TempDir(), "list.db")
	contract := success(t, db, "schema")
	responses := contract["responses"].(map[string]any)
	check := func(name string, args ...string) map[string]any {
		t.Helper()
		v := success(t, db, args...)
		if err := checkShape(v, responses[name].(map[string]any), name); err != nil {
			t.Fatal(err)
		}
		return v
	}
	a := check("add", "add", "--title", "Example", "--kind", "media", "--quality", "1")
	id := a["id"].(string)
	check("edit", "edit", id, "--unset-rating", "quality,interest")
	check("suggest", "suggest", "--peek", "--explain")
	check("list", "list")
	check("show", "show", id)
	for _, verb := range []string{"start", "done", "drop", "reopen"} {
		check(verb, verb, id)
	}
	check("edit", "edit", id, "--remaining-duration", "1h", "--cost", "10")
	check("start", "start", id)
	check("log", "log", id, "15m", "--cost", "2")
	check("deps", "deps", "list", id)
	check("config", "config")
	snapshot := filepath.Join(t.TempDir(), "snapshot.db")
	check("snapshot", "snapshot", snapshot)
	check("sync", "sync", snapshot, "--dry-run")
	exported := check("export json", "export", "json")
	data, err := json.Marshal(exported)
	if err != nil {
		t.Fatal(err)
	}
	file := filepath.Join(t.TempDir(), "export.json")
	if err = os.WriteFile(file, data, 0600); err != nil {
		t.Fatal(err)
	}
	check("import", "import", file, "--dry-run")
	check("doctor", "doctor")
	check("version", "version")
	_, _, stderr := invoke(t, db, "--effort", "tiny")
	var errorValue any
	if err = json.Unmarshal([]byte(stderr), &errorValue); err != nil {
		t.Fatal(err)
	}
	if err = checkShape(errorValue, responses["error"].(map[string]any), "error"); err != nil {
		t.Fatal(err)
	}
	root := contract["commands"].(map[string]any)
	for _, raw := range root["commands"].([]any) {
		n := raw.(map[string]any)
		if n["name"] == "suggest" {
			for _, raw := range n["flags"].([]any) {
				f := raw.(map[string]any)
				if f["name"] == "effort" {
					allowed, _ := f["allowed"].([]any)
					names := make([]string, 0, len(allowed))
					for _, a := range allowed {
						names = append(names, a.(string))
					}
					if !reflect.DeepEqual(names, effortAllowed) {
						t.Fatal(f)
					}
				}
			}
		}
	}
}

// TestSchemaAgentDiscoverability protects the semantic layer above the parser
// mechanics. An automation client should be able to construct safe invocations
// and understand their effects without scraping localized help text.
func TestSchemaAgentDiscoverability(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	contract := success(t, filepath.Join(t.TempDir(), "missing.db"), "schema")
	if contract["description"] == "" || contract["default_command"] != "suggest" || contract["default_invocation"] == "" {
		t.Fatalf("missing purpose/default metadata: %v", contract)
	}

	root := contract["commands"].(map[string]any)
	commands := map[string]map[string]any{}
	for _, raw := range root["commands"].([]any) {
		n := raw.(map[string]any)
		commands[n["name"].(string)] = n
		if n["description"] == "" || n["state_change"] == "" || n["output"] == nil {
			t.Errorf("command lacks semantics: %v", n["name"])
		}
	}
	for _, name := range []string{"add", "suggest", "list", "show", "start", "done", "drop", "reopen", "log", "deps"} {
		if commands[name] == nil {
			t.Fatalf("missing command %s", name)
		}
	}
	suggestChange := commands["suggest"]["state_change"].(map[string]any)
	if suggestChange["classification"] != "conditional" || !strings.Contains(suggestChange["description"].(string), "--peek") || !strings.Contains(commands["deps"]["description"].(string), "target item depends") {
		t.Fatal("conditional suggestion/dependency direction is undiscoverable")
	}

	arguments := func(command string) []map[string]any {
		out := []map[string]any{}
		for _, raw := range commands[command]["arguments"].([]any) {
			out = append(out, raw.(map[string]any))
		}
		return out
	}
	if got := arguments("deps"); len(got) != 3 || got[1]["name"] != "target" || got[2]["name"] != "dependencies" || got[2]["variadic"] != true {
		t.Fatalf("ambiguous dependency arguments: %v", got)
	}
	if got := arguments("start"); len(got) != 1 || got[0]["name"] != "items" || got[0]["variadic"] != true {
		t.Fatalf("ambiguous repeated item arguments: %v", got)
	}
	if got := arguments("log"); got[0]["name"] != "item" || got[1]["format"] != "duration" || got[1]["examples"] == nil {
		t.Fatalf("log arguments lack roles/formats: %v", got)
	}

	flags := func(command string) map[string]map[string]any {
		out := map[string]map[string]any{}
		for _, raw := range commands[command]["flags"].([]any) {
			f := raw.(map[string]any)
			out[f["name"].(string)] = f
		}
		return out
	}
	addFlags := flags("add")
	for _, name := range []string{"tag", "depends-on", "modes", "engagements", "unset-rating"} {
		if addFlags[name]["repeatable"] != true || addFlags[name]["collection"] == nil {
			t.Errorf("%s does not expose repeated/list syntax: %v", name, addFlags[name])
		}
	}
	for _, name := range []string{"clear-deadline", "clear-remaining-duration", "clear-cost", "clear-min-session-duration", "clear-total-duration"} {
		if !strings.Contains(addFlags[name]["description"].(string), "unknown/null") || addFlags[name]["examples"] == nil {
			t.Errorf("%s does not explain nullable clearing: %v", name, addFlags[name])
		}
	}
	queryFlags := flags("suggest")
	if queryFlags["session"]["examples"] == nil || !strings.Contains(queryFlags["effort"]["description"].(string), "Maximum") || !strings.Contains(queryFlags["unknown"]["description"].(string), "filter_evidence") {
		t.Fatal("query controls lack agent-facing semantics")
	}

	formats := contract["formats"].(map[string]any)
	duration := formats["duration"].(map[string]any)
	if !strings.Contains(duration["description"].(string), "Nonzero values require a unit") || duration["examples"] == nil {
		t.Fatalf("duration grammar is ambiguous: %v", duration)
	}
	properties := contract["property_definitions"].(map[string]any)
	for _, name := range []string{"intensity", "interest", "actuality", "influence", "quality"} {
		d := properties[name].(map[string]any)["description"].(string)
		if !strings.Contains(d, "0=") || !strings.Contains(d, "1=") {
			t.Errorf("%s has no rating direction: %q", name, d)
		}
	}
	concepts := contract["concepts"].(map[string]any)
	for _, name := range []string{"effort", "mode", "engagement", "readiness", "dependencies", "unknown_property_policy", "scoring", "nullable_fields"} {
		if concepts[name] == nil {
			t.Errorf("missing concept %s", name)
		}
	}
	if contract["error_definitions"] == nil || contract["exit_codes"] == nil || contract["responses"] == nil {
		t.Fatal("errors, exits, or response schemas are missing")
	}
}

func TestShellCompletion(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	for _, shell := range []string{"bash", "zsh", "fish"} {
		t.Run(shell, func(t *testing.T) {
			binary, err := exec.LookPath(shell)
			if err != nil {
				t.Skip("shell unavailable")
			}
			in, err := os.Open(os.DevNull)
			if err != nil {
				t.Fatal(err)
			}
			defer in.Close()
			var script, stderr bytes.Buffer
			if code := Run([]string{"completion", shell}, in, &script, &stderr); code != 0 {
				t.Fatal(code, stderr.String())
			}
			cmd := exec.Command(binary, "-n")
			cmd.Stdin = bytes.NewReader(script.Bytes())
			if out, err := cmd.CombinedOutput(); err != nil {
				t.Fatal(err, string(out))
			}
			if shell == "bash" {
				script.WriteString("\nCOMP_WORDS=(do-something --effort l)\nCOMP_CWORD=2\n_do_something\nprintf '%s' \"${COMPREPLY[*]}\"\n")
				cmd = exec.Command(binary)
				cmd.Stdin = &script
				out, err := cmd.CombinedOutput()
				if err != nil || string(out) != "low" {
					t.Fatalf("%q %v", out, err)
				}
			}
		})
	}
}
